description: cifar100_xd_eval_fixed

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

  
bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: cifar100
  train: false
  permute: false

  #NN architecture backbone
  backbone: 40,4
  droprate: 0.0

  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  nesterov: true

  #tuned
  arch_lr: 0.00001
  arch_adam: true

  global_batch_size: 128

  start_epoch: 0
  epochs: 200

  patch: true
  from_scratch: false
  
  #tuned
  kmatrix_depth: 3
  max_kernel_size: 3

  warmup_epochs: 50
  cooldown_epochs: 0

resources:
  slots_per_trial: 1

records_per_epoch: 50000
# 50000 if cifar, 60000 if spherical

searcher:
  name: single
  metric: top1_accuracy
  smaller_is_better: false 
  max_length:
    epochs: 200

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_point:XDTrial
