description: ninapro_xd_eval

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: ninapro
  train: false
  permute: false

  #NN architecture backbone
  #layers: 16
  #widen_factor: 4
  backbone: 40,2 
  droprate: 0.0

  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 5e-4 
  nesterov: true

  arch_lr: 0.0013246974647468438 
  arch_adam: false

  global_batch_size: 128

  start_epoch: 0
  epochs: 200

  patch: true
  from_scratch: false
  kmatrix_depth: 1
  max_kernel_size: 1

  warmup_epochs: 0 
 
  cooldown_epochs: 0

resources:
  slots_per_trial: 1

records_per_epoch: 3297 


searcher:
  name: single 
  metric: top1_accuracy
  smaller_is_better: false
  max_length: 
    epochs: 200

min_validation_period: 
  epochs: 1    
min_checkpoint_period:
  epochs: 5
         

max_restarts: 100

entrypoint: model_point:XDTrial
