description: protein_xd_eval
environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

hyperparameters:
  task: protein
  train: false
  droprate: 0.0

  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 5e-4
  nesterov: true

  #tuned
  arch_lr: 0.0001

  #tuned
  arch_adam: true
  
  global_batch_size: 8
  eval_batch_size: 2

  start_epoch: 0
  epochs: 200

  patch: true 
  from_scratch: false

  #tuned
  kmatrix_depth: 3
  max_kernel_size: 3

  warmup_epochs: 0
  cooldown_epochs: 0
  sub: 5

resources:
  slots_per_trial: 1

records_per_epoch: 3456

searcher:
  name: single
  metric: mae
  max_length:
    epochs: 200
  

min_validation_period:
  epochs: 40

max_restarts: 100

entrypoint: model_grid:XDTrial
