description: protein_backbone_eval
environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0 

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

hyperparameters:
  task: protein
  train: true
  #only because we don't have test set yet

  learning_rate: 0.0001
  weight_decay: 1e-4

  #tuned
  arch_lr: 0.0

  arch_momentum: 0.5

  #tuned
  arch_adam: false
  
  global_batch_size: 4

  start_epoch: 0
  epochs: 100

  patch: false 
  from_scratch: false
  kmatrix_depth: 1
  max_kernel_size: 1

  warmup_epochs: 0
  cooldown_epochs: 0
  sub: 5

resources:
  slots_per_trial: 1
  max_slots: 4

records_per_epoch: 3356

searcher:
  name: single
  metric: validation_loss
  max_length:
    epochs: 100
  

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_grid:XDTrial
