description: xd-vision-tuning

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo


data:
  download_dir: /data

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  # Number of classes in dataset
  n_classes: 10
  permute: false

  #NN architecture backbone
  layers: 40
  widen_factor: 2
  droprate: 0.0

  arch_lr:
    type: log
    minval: -5.0
    maxval: 0.0
    base: 10.0
  momentum: 0.9
  weight_decay: 1e-4
  learning_rate: 1e-4
  arch_adam: true
  global_batch_size: 128 

  start_epoch: 0
  epochs: 200


  patch: true
  from_scratch: false
  kmatrix_depth: 1
  max_kernel_size: 5

  warmup_epochs: 50
  cooldown_epochs: 0



records_per_epoch: 50000

searcher:
  name: adaptive_asha
  metric: validation_error
  max_length:
    epochs: 64
  max_trials: 16

min_validation_period:
  epochs: 1

max_restarts: 10

entrypoint: model_vision:XDTrial
