description: pde-xd-search
environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo


data:
  download_dir: /data
  type: s3
  bucket: pde-xd

hyperparameters:
  task: pde
  train: false

  learning_rate: 0.0001
  weight_decay: 1e-4
  arch_lr: 0.1
  arch_momentum: 0.5
  arch_adam: false

  global_batch_size: 4

  start_epoch: 0
  epochs: 100

  patch: false
  from_scratch: false
  kmatrix_depth: 1
  max_kernel_size: 1

  warmup_epochs: 0
  cooldown_epochs: 0
  
  sub: 5
resources:
  slots_per_trial: 1

records_per_epoch: 900

searcher:
  name: single
  metric: validation_loss
  max_length:
    epochs: 100

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_grid:XDTrial
