description: pde-xd-search

  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo


data:
  download_dir: /data
  type: s3
  bucket: pde-xd

hyperparameters:
  task: pde
  train: false

  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 1e-4
  arch_lr: 0.1
  arch_momentum: 0.5
  arch_adam: false

  global_batch_size: 10

  start_epoch: 0
  epochs: 500

  patch: true
  from_scratch: false
  kmatrix_depth: 1
  max_kernel_size: 1

  warmup_epochs: 0
  cooldown_epochs: 0

resources:
  slots_per_trial: 1

records_per_epoch: 900

searcher:
  name: single
  metric: validation_error
  max_length:
    epochs: 500

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_pde:XDTrial
