description: darts_cnn_nas

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo


data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

min_validation_period:
  batches: 100

hyperparameters:
    task: sEMG
    permute: false

    auxiliary: false
    auxiliary_weight: 0.4
    clip_gradients_l2_norm: 5
    cutout: false
    cutout_length: 16
    drop_path_prob: 0.2
    global_batch_size: 96
    init_channels: 16
    layers: 10
    learning_rate: 0.025
    momentum: 0.9
    normal_node1_edge1: 1
    normal_node1_edge1_op: sep_conv_3x3
    normal_node1_edge2: 1
    normal_node1_edge2_op: sep_conv_3x3
    normal_node2_edge1: 0
    normal_node2_edge1_op: skip_connect
    normal_node2_edge2: 1
    normal_node2_edge2_op: dil_conv_3x3
    normal_node3_edge1: 0
    normal_node3_edge1_op: sep_conv_3x3
    normal_node3_edge2: 0
    normal_node3_edge2_op: dil_conv_3x3
    normal_node4_edge1: 0
    normal_node4_edge1_op: max_pool_3x3
    normal_node4_edge2: 0
    normal_node4_edge2_op: sep_conv_3x3
    reduce_node1_edge1: 1
    reduce_node1_edge1_op: dil_conv_3x3
    reduce_node1_edge2: 1
    reduce_node1_edge2_op: max_pool_3x3
    reduce_node2_edge1: 2
    reduce_node2_edge1_op: skip_connect
    reduce_node2_edge2: 0
    reduce_node2_edge2_op: dil_conv_3x3
    reduce_node3_edge1: 1
    reduce_node3_edge1_op: sep_conv_3x3
    reduce_node3_edge2: 1
    reduce_node3_edge2_op: max_pool_3x3
    reduce_node4_edge1: 0
    reduce_node4_edge1_op: max_pool_3x3
    reduce_node4_edge2: 4
    reduce_node4_edge2_op: sep_conv_3x3
    train_epochs: 600
    weight_decay: 0.0003
scheduling_unit: 100

records_per_epoch: 50000


searcher:
  name: single
  metric: top1_accuracy
  smaller_is_better: false
  # 50k examples in train, 96 examples per batch, 100 batches per step -> 300 epochs ~ 1562 steps
  max_length:
    epochs: 200

entrypoint: model_def:DARTSCNNTrial
