description: pde_xd_random
environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0


data:
  download_dir: /data
  type: s3
  bucket: pde-xd

hyperparameters:
  task: pde
  train: false
  droprate: 0.0

  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 5e-4
  nesterov: true

  arch_lr:
    type: log
    minval: -6.0
    maxval: -2.0
    base: 10.0


  arch_adam: 
    type: categorical
    vals:
      - true
      - false

  global_batch_size: 4

  start_epoch: 0
  epochs: 200

  patch: true
  from_scratch: false
  kmatrix_depth: 
    type: categorical
    vals:
      - 1
      - 3
      - 5
  max_kernel_size: 1

  warmup_epochs: 0
  cooldown_epochs: 0
  sub: 5

resources:
  slots_per_trial: 1
  max_slots: 8

records_per_epoch: 1000

searcher:
  name: random
  metric: validation_loss
  max_length:
    epochs: 200
  max_trials: 8

  

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_grid:XDTrial
