description: protein_gaea_eval_seed2

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
    task: protein
    train: false

    # Number of classes in dataset
    n_classes: 1
    # Channel shuffle factor.  1 / shuffle_factor channels are activated at a given time.
    shuffle_factor: 4
    global_batch_size: 4
    learning_rate: 0.025
    momentum: 0.9
    min_learning_rate: 0
    scheduler_epochs: 600
    weight_decay: 3e-4
    arch_learning_rate: 0.0
    init_channels: 36 
    layers: 20
    nodes: 4
    multiplier: 4
    drop_path_prob: 0.3
    clip_gradients_l2_norm: 5

    sub: 5

resources:
  slots_per_trial: 1

min_validation_period: 
  epochs: 10

min_checkpoint_period:
  epochs: 5

records_per_epoch: 3456
searcher:
  name: single
  metric: lr8
  max_length: 
    epochs: 600

optimizations:
  aggregation_frequency:  1
max_restarts: 100

entrypoint: model_def:GAEASearchTrial
