description: audio_gaea_eval_2

environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: audio
  permute: false 

  learning_rate: 0.025
  momentum: 0.9
  weight_decay: 3e-4

  init_channels: 16
  layers: 20
  global_batch_size: 32
  drop_path_prob: 0.3
  clip_gradients_l2_norm: 5

resources:
  slots_per_trial: 1

min_validation_period:
  epochs: 75

min_checkpoint_period:
  epochs: 5

records_per_epoch: 40966

searcher:
  name: single
  metric: test_mAP
  max_length:
    epochs: 150

optimizations:
  aggregation_frequency:  1

max_restarts: 10

entrypoint: model_audio:GAEAEvalTrial
