description: xd-nas

#provider:
#  container_startup_script: |
#      export HOME=/root
#      apt-get update && apt-get install -y curl docker.io
#      apt install amazon-ecr-credential-helper
#      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 212469337107.dkr.ecr.us-east-1.amazonaws.com

#environment:
#  image: "212469337107.dkr.ecr.us-east-1.amazonaws.com/xd:determined"

environment:
  image: "renbotu/xd-nas:determined"
  registry_auth:
    username: renbotu
    password: 980715tutubo


data:
  download_dir: /data

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  # Number of classes in dataset
  n_classes: 10
  permute: false

  #NN architecture backbone
  layers: 40
  widen_factor: 2
  droprate: 0.0

  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  arch_lr: 0.1

  global_batch_size: 128 

  start_epoch: 0
  epochs: 200

  patch: true
  perturb: 0.0
  from_scratch: false

  warmup_epochs: 0
  cooldown_epochs: 0

resources:
  slots_per_trial: 1

records_per_epoch: 50000

searcher:
  name: single
  metric: validation_error
  max_length:
    epochs: 200

min_validation_period:
  epochs: 1

max_restarts: 10

entrypoint: backbone_determined:NASTrial
