description: permuted_gaea_search_seed2

environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
    task: cifar100
    permute: true

    # Channel shuffle factor.  1 / shuffle_factor channels are activated at a given time.
    shuffle_factor: 4
    global_batch_size: 256
    
    # these are default values
    learning_rate: 0.1
    momentum: 0.9
    min_learning_rate: 0
    scheduler_epochs: 50
    weight_decay: 3e-4
    arch_learning_rate: 0.1
    init_channels: 16
    layers: 8
    nodes: 4
    clip_gradients_l2_norm: 5

resources:
  slots_per_trial: 1

min_validation_period: 
  epochs: 1

min_checkpoint_period:
  epochs: 2

records_per_epoch: 20000
searcher:
  name: single
  metric: top1_accuracy 
  smaller_is_better: false 
  max_length: 
    epochs: 50

optimizations:
  aggregation_frequency:  1

max_restarts: 1000

entrypoint: model_def:GAEASearchTrial
