description: scifar100_xd_search_distributed

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

  
bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: scifar100
  train: false  
  permute: false

  #NN architecture backbone
  #layers: 16
  #widen_factor: 4
  #backbone: 
  #  type: categorical
  #  vals:
  #    - 40,2
  #    - 16,4
  backbone: 28,4
  droprate: 0.0

  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 5e-4 
  nesterov: true

  arch_lr: 0.001 

  arch_adam: true

  global_batch_size: 64

  start_epoch: 0
  epochs: 200

  patch: true
  from_scratch: false
  kmatrix_depth: 5
    
  max_kernel_size: 1

  warmup_epochs: 0 
 
  cooldown_epochs: 0

resources:
  slots_per_trial: 4
  max_slots: 16

records_per_epoch: 40000
# 50000 if cifar, 60000 if spherical


searcher:
  name: single
  metric: top1_accuracy
  smaller_is_better: false
  max_length:
    epochs: 200

min_validation_period:
  epochs: 20

min_checkpoint_period:
  epochs: 5
         
optimizations:
   # Gradient updates will be communicated every 4 mini-batches.
   aggregation_frequency: 4

max_restarts: 100

entrypoint: model_point:XDTrial
