description: gaea_search

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
    # Number of classes in dataset
    n_classes: 1
    # Channel shuffle factor.  1 / shuffle_factor channels are activated at a given time.
    shuffle_factor: 1
    global_batch_size: 20
    learning_rate: 0.025
    momentum: 0.9
    min_learning_rate: 0
    scheduler_epochs: 50
    weight_decay: 3e-4
    arch_learning_rate: 0.1
    init_channels: 16
    layers: 4
    nodes: 4
    multiplier: 1

    width: 32
    sub: 5

resources:
  slots_per_trial: 1

min_validation_period: 
  batches: 50

records_per_epoch: 1000
searcher:
  name: single
  metric: validation_error 
  max_length: 
    epochs: 50

optimizations:
  aggregation_frequency:  1

entrypoint: model_def:GAEASearchTrial
