description: pde_gaea_eval

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
    task: pde
    train: false

    # Number of classes in dataset
    n_classes: 1
    # Channel shuffle factor.  1 / shuffle_factor channels are activated at a given time.
    shuffle_factor: 4
    global_batch_size: 16
    learning_rate: 0.025
    momentum: 0.9
    min_learning_rate: 0
    scheduler_epochs: 50
    weight_decay: 3e-4
    arch_learning_rate: 0.0
    #init_channels: 16
    init_channels: 32 #from pde
    layers: 20
    nodes: 4
    multiplier: 1
    drop_path_prob: 0.3
    clip_gradients_l2_norm: 5

    width: 32
    sub: 5

resources:
  slots_per_trial: 1

min_validation_period: 
  epochs: 1

min_checkpoint_period:
  epochs: 1

records_per_epoch: 500
searcher:
  name: single
  metric: validation_error 
  max_length: 
    epochs: 200

optimizations:
  aggregation_frequency:  1

entrypoint: model_def:GAEASearchTrial
