description: protein_gaea_search

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
    task: protein
    train: true

    # Channel shuffle factor.  1 / shuffle_factor channels are activated at a given time.
    shuffle_factor: 4
    global_batch_size: 4
    learning_rate: 0.1
    momentum: 0.9
    min_learning_rate: 0
    scheduler_epochs: 50
    weight_decay: 3e-4
    arch_learning_rate: 0.1
    #init_channels: 16
    init_channels: 16 #from pde
    layers: 8
    nodes: 4
    multiplier: 4
    width: 32
    sub: 5
    clip_gradients_l2_norm: 5

resources:
  slots_per_trial: 1

min_validation_period: 
  epochs: 1

min_checkpoint_period:
  epochs: 2

records_per_epoch: 1628 
searcher:
  name: single
  metric: MAE 
  max_length: 
    epochs: 50

optimizations:
  aggregation_frequency:  1

entrypoint: model_def:GAEASearchTrial
