description: cifar100_xd_search_seed2

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

  
bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: cifar100
  train: true  
  permute: false

  #NN architecture backbone
  #layers: 16
  #widen_factor: 4
  #backbone: 
  #  type: categorical
  #  vals:
  #    - 40,2
  #    - 16,4
  backbone: 16,4
  
  droprate: 0.0

  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 5e-4 
  nesterov: true

  arch_lr: 
    type: log
    minval: -6.0
    maxval: -2.0
    base: 10.0

  arch_adam:
    type: categorical
    vals:
      - true
      - false

  global_batch_size: 128

  start_epoch: 0
  epochs: 200

  patch: true
  from_scratch: false

  kmatrix_depth:
    type: categorical
    vals:
      - 1
      - 3
      - 5
    
  max_kernel_size: 1

  warmup_epochs: 0 
 
  cooldown_epochs: 0

resources:
  slots_per_trial: 1
  max_slots: 3

records_per_epoch: 40000
# 50000 if cifar, 60000 if spherical


searcher:
  name: adaptive_asha
  metric: top1_accuracy
  smaller_is_better: false
  max_length:
    epochs: 200
  max_trials: 16
  mode: aggressive
  divisor: 4
  max_rungs: 5
  max_concurrent_trials: 3

min_validation_period:
  epochs: 2

min_checkpoint_period:
  epochs: 5
         

max_restarts: 100

entrypoint: model_point:XDTrial
