# NOTE: this config uses randomly generated data on single GPU.
# Please use distributed.yaml if you want to run on the
# the actual imagenet data.
description: cifar100_gaea_eval_aux

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

  num_workers_train: 2
  num_workers_val: 2

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: cifar100
  permute: false 

  learning_rate: 0.025
  momentum: 0.9
  weight_decay: 3e-4

  init_channels: 36
  layers: 20
  global_batch_size: 128
  drop_path_prob: 0.3
  clip_gradients_l2_norm: 5

resources:
  slots_per_trial: 1

min_validation_period:
  epochs: 1

min_checkpoint_period:
  epochs: 2

records_per_epoch: 50000 

searcher:
  name: single
  metric: top1_accuracy 
  smaller_is_better: false 
  max_length:
    epochs: 600

optimizations:
  aggregation_frequency:  1

max_restarts: 1000

entrypoint: model_aux:GAEAEvalTrial
