description: audio_backbone_retrain_2

environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: audio
  train: false
  permute: false

  #NN architecture backbone
  backbone: 16,4
  droprate: 0.0

  learning_rate: 0.07828043678894522
  momentum: 0.9
  weight_decay: 0.00004485488828040062
  nesterov: true

  global_batch_size: 256

  start_epoch: 0
  epochs: 200

resources:
  slots_per_trial: 1

records_per_epoch: 40966 

searcher:
  name: single
  #metric: val_mAP
  metric: test_mAP
  max_length:
    epochs: 200

min_validation_period:
  epochs: 100

min_checkpoint_period:
  epochs: 5

max_restarts: 100

entrypoint: model_audio:BackboneTrial
