description: cosmic_fno_eval_2
environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: cosmic
  backbone: 16,4
  train: false
  droprate: 0.0

  learning_rate: 0.07828043678894522
  momentum: 0.9
  weight_decay: 0.00004485488828040062
  nesterov: true

  global_batch_size: 8

  start_epoch: 0
  epochs: 500

  sub: 5

  in_channels: 1

resources:
  slots_per_trial: 1

records_per_epoch: 4830

searcher:
  name: single
  metric: TPR
  smaller_is_better: false
  max_length:
    epochs: 500
  

min_validation_period:
  epochs: 20

min_checkpoint_period:
  epochs: 5

max_restarts: 100

entrypoint: model_grid_fno:BackboneTrial
