description: ninapro_backbone_retrain

environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: ninapro
  train: false
  permute: false

  #NN architecture backbone
  backbone: 16,4
  droprate: 0.3

  learning_rate: 0.07058512048254169
  momentum: 0.9
  weight_decay: 0.0029038868465087945
  nesterov: true

  global_batch_size: 128

  start_epoch: 0
  epochs: 200

resources:
  slots_per_trial: 1

records_per_epoch: 3297


searcher:
  name: single 
  metric: top1_accuracy
  smaller_is_better: false
  max_length: 
    epochs: 200

min_validation_period: 
  epochs: 5
min_checkpoint_period:
  epochs: 5
         

max_restarts: 100

entrypoint: model_point:BackboneTrial
