description: pde_backbone_eval_2
environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: pde
  train: true
  backbone: 16,4
  droprate: 0.0

  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 5e-4
  nesterov: true

  global_batch_size: 8

  start_epoch: 0
  epochs: 200

  sub: 5

resources:
  slots_per_trial: 1

records_per_epoch: 900

searcher:
  name: single
  metric: validation_loss
  max_length:
    epochs: 200

min_validation_period:
  epochs: 5

max_restarts: 100

entrypoint: model_grid_original:BackboneTrial
