description: pde_backbone_retrain
environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0 

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false
hyperparameters:
  task: pde
  train: false
  droprate: 0.3

  learning_rate: 0.040978885541880554
  momentum: 0.9
  weight_decay: 0.00006942729492430138
  nesterov: true

  global_batch_size: 4

  start_epoch: 0
  epochs: 200

  sub: 5

resources:
  slots_per_trial: 1

records_per_epoch: 1000

searcher:
  name: single
  metric: validation_loss
  max_length:
    epochs: 200
  

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_grid_original:BackboneTrial
