description: pde_backbone_retrain_seed2
environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false
hyperparameters:
  task: pde
  train: false
  backbone: 16,4
  droprate: 0.3

  learning_rate: 0.009483034914203466
  momentum: 0.9
  weight_decay: 0.0000510432706737419
  nesterov: true

  global_batch_size: 4
  eval_batch_size: 4

  start_epoch: 0
  epochs: 200

  sub: 5

resources:
  slots_per_trial: 1

records_per_epoch: 1000

searcher:
  name: single
  metric: validation_loss
  max_length:
    epochs: 200
  

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_grid_original:BackboneTrial
