description: permuted_backbone_eval_seed1

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 1 

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

  
bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: cifar100
  train: true
  permute: true

  #NN architecture backbone
  backbone: 16,4
  droprate: 0.0

  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  nesterov: true

  global_batch_size: 128

  start_epoch: 0
  epochs: 200


resources:
  slots_per_trial: 1

records_per_epoch: 40000

searcher:
  name: single
  metric: top1_accuracy
  smaller_is_better: false 
  max_length:
    epochs: 200

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_point:BackboneTrial
