description: protein_backbone_retrain_seed2
environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: protein
  train: false
  droprate: 0.3

  learning_rate: 0.0026485886617388914
  momentum: 0.9
  weight_decay: 0.00011955154427905232
  nesterov: true

  global_batch_size: 8
  eval_batch_size: 2

  start_epoch: 0
  epochs: 200

  sub: 5

resources:
  slots_per_trial: 1

records_per_epoch: 3456

searcher:
  name: single
  metric: mae
  max_length:
    epochs: 200
  

min_validation_period:
  epochs: 20

max_restarts: 100

entrypoint: model_grid_original:BackboneTrial
