description: protein_backbone_eval
environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0 

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

hyperparameters:
  task: protein
  train: false

  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 1e-4
  nesterov: true

  global_batch_size: 8
  eval_batch_size: 2

  start_epoch: 0
  epochs: 100

  sub: 5

resources:
  slots_per_trial: 1
  max_slots: 4

records_per_epoch: 3456

searcher:
  name: single
  metric: mae
  max_length:
    epochs: 100
  

min_validation_period:
  epochs: 1

max_restarts: 100

entrypoint: model_grid:BackboneTrial
