description: protein_backbone_retrain
environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: protein
  backbone: 16,4
  train: false
  droprate: 0.3

  learning_rate: 0.012384930898256393
  momentum: 0.3
  weight_decay: 0.00811759169863413 
  nesterov: true

  global_batch_size: 8
  eval_batch_size: 2

  start_epoch: 0
  epochs: 200

  sub: 5

resources:
  slots_per_trial: 1

records_per_epoch: 3456

searcher:
  name: single
  metric: mae
  max_length:
    epochs: 200
  

min_validation_period:
  epochs: 20

min_checkpoint_period:
  epochs: 5

max_restarts: 100

entrypoint: model_grid_original:BackboneTrial
