description: scifar100_backbone_retrain_2

environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

  
bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: scifar100
  train: false
  permute: false 

  #NN architecture backbone
  backbone: 16,4
  droprate: 0.6

  learning_rate: 0.026762449321952597
  momentum: 0.6
  weight_decay: 0.0021363753335547383 
  nesterov: true

  global_batch_size: 128

  start_epoch: 0
  epochs: 200


resources:
  slots_per_trial: 1

records_per_epoch: 50000


searcher:
  name: single
  metric: top1_accuracy
  smaller_is_better: false
  max_length:
    epochs: 200

min_validation_period:
  epochs: 20

min_checkpoint_period:
  epochs: 5
         

max_restarts: 100

entrypoint: model_point:BackboneTrial
