description: scifar100_backbone_retrain_seed1

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 1

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

  
bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: scifar100
  train: false
  permute: false 

  #NN architecture backbone
  #layers: 16
  #widen_factor: 4
  backbone: 16,4
  droprate: 0.3

  learning_rate: 0.9744044165384413
  momentum: 0
  weight_decay: 0.000010010539860510488
  nesterov: true

  global_batch_size: 128

  start_epoch: 0
  epochs: 200


resources:
  slots_per_trial: 1
  max_slots: 4

records_per_epoch: 50000


searcher:
  name: single
  metric: top1_accuracy
  smaller_is_better: false
  max_length:
    epochs: 200

min_validation_period:
  epochs: 1

min_checkpoint_period:
  epochs: 5
         

max_restarts: 100

entrypoint: model_point:BackboneTrial
