description: ECG_backbone_eval_2

environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 2

data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: ECG
  train: false

  #NN architecture backbone
  learning_rate: 0.003038858737081515
  momentum: 0.9
  weight_decay: 0.00003395892008889067
  nesterov: true

  global_batch_size: 256

  start_epoch: 0
  epochs: 200

resources:
  slots_per_trial: 1

records_per_epoch: 295021 

searcher:
  name: single
  metric: score
  smaller_is_better: false 
  max_length:
    epochs: 200

min_validation_period:
  epochs: 20

min_checkpoint_period:
  epochs: 5

max_restarts: 100

entrypoint: model_def:BackboneTrial

