description: ninapro_asha_search

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo


data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

min_validation_period:
  epochs: 1

min_checkpoint_period: 
  epochs: 1

hyperparameters:
  task: ninapro
  permute: false
  train: true

  learning_rate: 0.025
  #type: log
  #minval: -2.0
  #maxval: 0.0
  #base: 10.0 
 
  momentum: 0.9
  #type: double
  #minval: 0.0
  #maxval: 0.9

  weight_decay: 0.0003
  #type: log
  #minval: -4.0
  #maxval: -2.0
  #base: 10.0

  train_epochs: 200
  global_batch_size: 128
  init_channels: 36
  layers: 20
  auxiliary: false
  auxiliary_weight: 0.4
  cutout: false
  cutout_length: 16
  drop_path_prob: 0.3
  clip_gradients_l2_norm: 5

  # Tunable hyperparameters
  # Normal cell
  normal_node1_edge1:
    type: categorical
    vals: [0, 1]
  normal_node1_edge2:
    type: categorical
    vals: [0, 1]
  normal_node2_edge1:
    type: categorical
    vals: [0, 1, 2]
  normal_node2_edge2:
    type: categorical
    vals: [0, 1, 2]
  normal_node3_edge1:
    type: categorical
    vals: [0, 1, 2, 3]
  normal_node3_edge2:
    type: categorical
    vals: [0, 1, 2, 3]
  normal_node4_edge1:
    type: categorical
    vals: [0, 1, 2, 3, 4]
  normal_node4_edge2:
    type: categorical
    vals: [0, 1, 2, 3, 4]
  normal_node1_edge1_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  normal_node1_edge2_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  normal_node2_edge1_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  normal_node2_edge2_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  normal_node3_edge1_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  normal_node3_edge2_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  normal_node4_edge1_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  normal_node4_edge2_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  # Reduce cell
  reduce_node1_edge1:
    type: categorical
    vals: [0, 1]
  reduce_node1_edge2:
    type: categorical
    vals: [0, 1]
  reduce_node2_edge1:
    type: categorical
    vals: [0, 1, 2]
  reduce_node2_edge2:
    type: categorical
    vals: [0, 1, 2]
  reduce_node3_edge1:
    type: categorical
    vals: [0, 1, 2, 3]
  reduce_node3_edge2:
    type: categorical
    vals: [0, 1, 2, 3]
  reduce_node4_edge1:
    type: categorical
    vals: [0, 1, 2, 3, 4]
  reduce_node4_edge2:
    type: categorical
    vals: [0, 1, 2, 3, 4]
  reduce_node1_edge1_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  reduce_node1_edge2_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  reduce_node2_edge1_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  reduce_node2_edge2_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  reduce_node3_edge1_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  reduce_node3_edge2_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  reduce_node4_edge1_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]
  reduce_node4_edge2_op:
    type: categorical
    vals: [max_pool_3x3, avg_pool_3x3, skip_connect, sep_conv_3x3, sep_conv_5x5, dil_conv_3x3, dil_conv_5x5]

resources:
  slots_per_trial: 1
  max_slots: 5

scheduling_unit: 100

records_per_epoch: 3560

searcher:
  name: adaptive_asha
  metric: top1_accuracy
  smaller_is_better: false
  max_length:
    epochs: 200
  max_trials: 32
  mode: aggressive
  # A maximum of 4 rungs corresponds to a minimum training length of 1/divisor^(max_rungs - 1) = 1/64 * max_length 
  # per trial.  Trials with higher validation accuracy will be trained for longer than this minimum will poor
  # trials will be stopped early.
  max_rungs: 5
  divisor: 4
 

entrypoint: model_def:DARTSCNNTrial

max_restarts: 100
