# NOTE: this config uses randomly generated data on single GPU.
# Please use distributed.yaml if you want to run on the
# the actual imagenet data.
description: gaea_eval_const 

environment:
  image: "renbotu/xd-nas:determined1.8"
  registry_auth:
    username: renbotu
    password: 980715tutubo

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd


bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
  task: spherical

  num_classes: 10
  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 3e-4

  init_channels: 16
  layers: 8
  # Set global_batch_size to 1024
  # if not using randomly generated data.
  global_batch_size: 64

resources:
  slots_per_trial: 1

min_validation_period:
  epochs: 1

min_checkpoint_period:
  epochs: 2

records_per_epoch: 60000

searcher:
  name: single
  metric: top1_accuracy 
  smaller_is_better: false 
  max_length:
    epochs: 50

optimizations:
  aggregation_frequency:  1

entrypoint: model_def:GAEAEvalTrial
