description: deepsea_gaea1d_search

environment:
  image: "renbotu/xd-nas:determined1.8"

reproducibility:
  experiment_seed: 0

data:
  download_dir: /data
  type: s3
  bucket: pde-xd

bind_mounts:
  - host_path: /tmp
    container_path: /data
    read_only: false

hyperparameters:
    task: deepsea

    # Number of classes in dataset
    n_classes: 36
    # Channel shuffle factor.  1 / shuffle_factor channels are activated at a given time.
    shuffle_factor: 4
    global_batch_size: 128
    learning_rate: 0.1
    momentum: 0.9
    min_learning_rate: 0
    scheduler_epochs: 50
    weight_decay: 3e-4
    arch_learning_rate: 0.1
    init_channels: 16
    layers: 8
    nodes: 4
    clip_gradients_l2_norm: 5

resources:
  slots_per_trial: 1

min_validation_period:
  epochs: 10

min_checkpoint_period:
  epochs: 10

records_per_epoch: 35877
searcher:
  name: single
  metric: test_mAUC
  smaller_is_better: false
  max_length:
    epochs: 50

optimizations:
  aggregation_frequency:  1

max_restarts: 1000

entrypoint: model_def:GAEASearchTrial
